/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.ProdutoVO;
import servicos.ProdutoServicos;
import servicos.ServicosFactory;

/**
 * @author Thiago Cury
 * @version 1.0
 */
public class UICadProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiCadProduto
     */
    public UICadProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlValorCusto = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtValorCusto = new javax.swing.JTextField();
        jtQuantidade = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("cadastro de produto");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");
        jLayeredPane1.add(jlNome);
        jlNome.setBounds(30, 50, 60, 14);

        jlValorCusto.setText("valor Custo");
        jLayeredPane1.add(jlValorCusto);
        jlValorCusto.setBounds(30, 110, 90, 14);

        jlQuantidade.setText("Quantidade");
        jLayeredPane1.add(jlQuantidade);
        jlQuantidade.setBounds(30, 170, 100, 14);
        jLayeredPane1.add(jtNome);
        jtNome.setBounds(140, 40, 210, 40);
        jLayeredPane1.add(jtValorCusto);
        jtValorCusto.setBounds(140, 100, 210, 40);
        jLayeredPane1.add(jtQuantidade);
        jtQuantidade.setBounds(140, 160, 210, 40);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbCadastrar);
        jbCadastrar.setBounds(30, 20, 140, 23);

        jbLimpar.setText("limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jbLimpar);
        jbLimpar.setBounds(210, 20, 140, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        try {
            ProdutoVO pVO = new ProdutoVO();
            pVO.setNome(jtNome.getText());
            pVO.setValorCusto(
                    Double.parseDouble(
                        jtValorCusto.getText()));
            pVO.setQuantidade(
                    Integer.parseInt(
                        jtQuantidade.getText()));
            
            ProdutoServicos ps = ServicosFactory.getProdutoServicos();
            
            ps.cadastrarProduto(pVO);
            
            JOptionPane.showMessageDialog(this,
                 "Produto cadastrado com sucesso!");
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "ERRO! "+e.getMessage());
        }
    }
    
    private void limpar(){
        jtNome.setText(null);
        jtQuantidade.setText(null);
        jtValorCusto.setText(null);
    }

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlValorCusto;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtQuantidade;
    private javax.swing.JTextField jtValorCusto;
    // End of variables declaration//GEN-END:variables
}
